project_id = "wxmewdwqeeejoetwyiem"

[functions.ingest-events]
verify_jwt = false

[functions.ingest-feeds]
verify_jwt = false

[functions.scrape-events]
verify_jwt = false

[functions.cleanup-events]
verify_jwt = false

[functions.monitor-feeds]
verify_jwt = false